#! /bin/bash

wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/eps08dta.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/cteq6mE.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/cteq6m.LHpdf
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/cteq6ll.LHpdf
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/cteq6lg.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/cteq6l.LHpdf
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/cteq6AB.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/cteq66c.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/cteq66alphas.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/cteq66a3.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/cteq66a2.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/cteq66a1.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/cteq66a0.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/cteq66.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/cteq65s.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/cteq65c.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/cteq65.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/cteq61.LHpdf
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/cteq61.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/cteq6.LHpdf
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/cteq5m1.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/cteq5m.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/cteq5l.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/cteq5f4.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/cteq5f3.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/cteq5d.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/cteq4m.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/cteq4l.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/cteq4d.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/abm12lhc_5_nnlo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/abm12lhc_4_nnlo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/abm12lhc_3_nnlo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/abm11_5n_nnlo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/abm11_5n_nlo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/abm11_5n_as_nnlo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/abm11_5n_as_nlo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/abm11_4n_nnlo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/abm11_4n_nlo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/abm11_3n_nnlo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/abm11_3n_nlo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/abkm09_5_nnlo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/abkm09_5_nlo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/abkm09_4_nnlo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/abkm09_4_nlo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/abkm09_3_nnlo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/abkm09_3_nlo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/a02m_nnlo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/a02m_nlo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/a02m_lo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/ZEUS2005_ZJ.LHpdf
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/ZEUS2002_ZM.LHpdf
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/ZEUS2002_TR.LHpdf
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/ZEUS2002_FF.LHpdf
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/WHITG.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/USERGRIDQ4.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/USERGRIDQ3.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/USERGRIDQ2.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/SMRSPI.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/SASG.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/OWPI.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDFpol10_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nnlo_noLHC_as_0120.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nnlo_noLHC_as_0119.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nnlo_noLHC_as_0118.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nnlo_noLHC_as_0117.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nnlo_noLHC_as_0116.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nnlo_collider_as_0120.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nnlo_collider_as_0119.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nnlo_collider_as_0118.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nnlo_collider_as_0117.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nnlo_collider_as_0116.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nnlo_as_0124.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nnlo_as_0123.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nnlo_as_0122.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nnlo_as_0121.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nnlo_as_0120.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nnlo_as_0119_qed_neutron.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nnlo_as_0119_qed.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nnlo_as_0119.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nnlo_as_0118_qed_neutron.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nnlo_as_0118_qed.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nnlo_as_0118.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nnlo_as_0117_qed_neutron.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nnlo_as_0117_qed.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nnlo_as_0117.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nnlo_as_0116.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nnlo_as_0115.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nnlo_as_0114.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nnlo_FFN_NF5_as_0120.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nnlo_FFN_NF5_as_0119.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nnlo_FFN_NF5_as_0118.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nnlo_FFN_NF5_as_0117.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nnlo_FFN_NF5_as_0116.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nnlo_FFN_NF4_as_0120.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nnlo_FFN_NF4_as_0119.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nnlo_FFN_NF4_as_0118.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nnlo_FFN_NF4_as_0117.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nnlo_FFN_NF4_as_0116.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_noLHC_as_0120.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_noLHC_as_0119.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_noLHC_as_0118.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_noLHC_as_0117.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_noLHC_as_0116.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_collider_as_0120.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_collider_as_0119.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_collider_as_0118.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_collider_as_0117.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_collider_as_0116.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_as_0124.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_as_0123.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_as_0122.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_as_0121.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_as_0120_mc.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_as_0120.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_as_0119_qed_neutron.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_as_0119_qed.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_as_0119_mc.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_as_0119.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_as_0118_qed_neutron.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_as_0118_qed.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_as_0118_mc.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_as_0118.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_as_0117_qed_neutron.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_as_0117_qed.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_as_0117_mc.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_as_0117.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_as_0116_mc.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_as_0116.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_as_0115.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_as_0114.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_FFN_NF5_as_0120_mc.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_FFN_NF5_as_0120.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_FFN_NF5_as_0119_mc.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_FFN_NF5_as_0119.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_FFN_NF5_as_0118_mc.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_FFN_NF5_as_0118.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_FFN_NF5_as_0117_mc.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_FFN_NF5_as_0117.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_FFN_NF5_as_0116_mc.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_FFN_NF5_as_0116.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_FFN_NF4_as_0120_mc.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_FFN_NF4_as_0120.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_FFN_NF4_as_0119_mc.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_FFN_NF4_as_0119.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_FFN_NF4_as_0118_mc.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_FFN_NF4_as_0118.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_FFN_NF4_as_0117_mc.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_FFN_NF4_as_0117.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_FFN_NF4_as_0116_mc.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_FFN_NF4_as_0116.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF22_nlo_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_nnlo_nf5_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_nnlo_mc_17_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_nnlo_mc_16_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_nnlo_mc_15_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_nnlo_mb_525_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_nnlo_mb_50_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_nnlo_mb_45_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_nnlo_mb_425_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_nnlo_heraonly_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_nnlo_dis_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_nnlo_dis+dy_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_nnlo_collider_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_nnlo_as_0124_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_nnlo_as_0123_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_nnlo_as_0122_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_nnlo_as_0121_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_nnlo_as_0120_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_nnlo_as_0118_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_nnlo_as_0117_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_nnlo_as_0116_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_nnlo_as_0115_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_nnlo_as_0114_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_nnlo_1000.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_nnlo_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_mc_17_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_mc_16_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_mc_15_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_mb_525_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_mb_50_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_mb_45_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_mb_425_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_lostar_as_0130_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_lostar_as_0119_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_lo_as_0130_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_lo_as_0119_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_dis_1000.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_dis_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_dis+jet_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_dis+dy_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_as_0124_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_as_0123_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_as_0122_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_as_0121_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_as_0120_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_as_0118_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_as_0117_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_as_0116_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_as_0115_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_as_0114_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_FFN_NF5_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_FFN_NF4_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_FFN_NF3_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_1000.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF21_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF20_heraold_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF20_dis_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF20_dis+jet_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF20_dis+dy_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF20_as_0124_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF20_as_0123_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF20_as_0122_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF20_as_0121_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF20_as_0120_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF20_as_0118_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF20_as_0117_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF20_as_0116_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF20_as_0115_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF20_as_0114_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF20_1000.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF20_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF12_1000.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF12_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF11_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF10_1000.LHpdf
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF10_1000.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF10_100.LHpdf
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF10_100.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nnlo_mcrange_nf3.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nnlo_mcrange_fixasmz_nf3.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nnlo_mcrange_fixasmz.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nnlo_mcrange.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nnlo_mbrange_nf4.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nnlo_mbrange.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nnlo_asmzrange.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nnlo90cl_nf4as5.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nnlo90cl_nf4.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nnlo90cl_nf3.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nnlo90cl_asmz-90clhalf.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nnlo90cl_asmz-90cl.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nnlo90cl_asmz+90clhalf.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nnlo90cl_asmz+90cl.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nnlo90cl.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nnlo68cl_nf4as5.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nnlo68cl_nf4.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nnlo68cl_nf3.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nnlo68cl_asmz-68clhalf.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nnlo68cl_asmz-68cl.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nnlo68cl_asmz+68clhalf.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nnlo68cl_asmz+68cl.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nnlo68cl.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nlo_mcrange_nf3.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nlo_mcrange_fixasmz_nf3.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nlo_mcrange_fixasmz.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nlo_mcrange.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nlo_mbrange_nf4.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nlo_mbrange.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nlo_asmzrange.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nlo90cl_nf4as5.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nlo90cl_nf4.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nlo90cl_nf3.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nlo90cl_asmz-90clhalf.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nlo90cl_asmz-90cl.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nlo90cl_asmz+90clhalf.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nlo90cl_asmz+90cl.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nlo90cl.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nlo68cl_nf4as5.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nlo68cl_nf4.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nlo68cl_nf3.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nlo68cl_asmz-68clhalf.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nlo68cl_asmz-68cl.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nlo68cl_asmz+68clhalf.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nlo68cl_asmz+68cl.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nlo68cl.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008lo90cl_nf4as5.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008lo90cl_nf4.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008lo90cl_nf3.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008lo90cl.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008lo68cl_nf4as5.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008lo68cl_nf4.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008lo68cl_nf3.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008lo68cl.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008CPdeutnnlo68cl.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008CPdeutnlo68cl.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MRSTMCal.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MRST98nlo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MRST98lo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MRST98ht.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MRST98dis.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MRST98.LHpdf
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MRST2007lomod.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MRST2006nnlo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MRST2004qed_proton.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MRST2004qed_neutron.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MRST2004qed.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MRST2004nnlo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MRST2004nlo.LHpdf
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MRST2004nlo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MRST2004FF4nlo.LHpdf
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MRST2004FF4nlo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MRST2004FF4lo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MRST2004FF3nlo.LHpdf
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MRST2004FF3nlo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MRST2004FF3lo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MRST2003cnnlo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MRST2003cnlo.LHpdf
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MRST2003cnlo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MRST2002nnlo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MRST2002nlo.LHpdf
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MRST2002nlo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MRST2001nnlo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MRST2001nlo.LHpdf
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MRST2001nlo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MRST2001lo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MRST2001E.LHpdf
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MRST2001E.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/LHECNLO_EIG.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/LACG.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/JR09VFnnloE.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/JR09FFnnloE.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/HKNnlo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/HKNlo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/HERAPDF15NNLO_VAR.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/HERAPDF15NNLO_EIG.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/HERAPDF15NNLO_ALPHAS.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/HERAPDF15NLO_VAR.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/HERAPDF15NLO_EIG.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/HERAPDF15NLO_ALPHAS.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/HERAPDF10_VAR.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/HERAPDF10_FFMOD.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/HERAPDF10_FF.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/HERAPDF10_EIG.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/HERAPDF10_ALPHAS.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/HERAPDF1.5LO_EIG.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/HERAPDF01.LHpdf
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/HERAPDF01.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/H12000msE.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/H12000ms.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/H12000loE.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/H12000lo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/H12000disE.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/H12000dis.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/GSG961.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/GSG960.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/GSG1.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/GSG0.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/GRVPI1.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/GRVPI0.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/GRVG1.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/GRVG0.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/GRV98nlo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/GRV98lo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/GJR08lo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/GJR08VFnloE.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/GJR08FFnloE.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/GJR08FFdis.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/Fermi2002_1000.LHpdf
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/Fermi2002_100.LHpdf
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/EPS09NLOR_9.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/EPS09NLOR_84.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/EPS09NLOR_64.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/EPS09NLOR_6.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/EPS09NLOR_56.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/EPS09NLOR_40.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/EPS09NLOR_4.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/EPS09NLOR_27.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/EPS09NLOR_238.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/EPS09NLOR_208.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/EPS09NLOR_20.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/EPS09NLOR_197.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/EPS09NLOR_195.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/EPS09NLOR_184.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/EPS09NLOR_16.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/EPS09NLOR_131.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/EPS09NLOR_12.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/EPS09NLOR_117.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/EPS09NLOR_115.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/EPS09NLOR_108.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/EPS09LOR_9.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/EPS09LOR_64.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/EPS09LOR_6.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/EPS09LOR_56.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/EPS09LOR_40.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/EPS09LOR_4.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/EPS09LOR_27.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/EPS09LOR_238.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/EPS09LOR_208.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/EPS09LOR_197.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/EPS09LOR_195.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/EPS09LOR_184.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/EPS09LOR_16.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/EPS09LOR_12.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/EPS09LOR_117.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/EPS09LOR_115.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/EPS09LOR_108.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/DOG1.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/DOG0.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/DGG.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10wnlo_nf4.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10wnlo_nf3.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10wnlo_as_0127.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10wnlo_as_0126.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10wnlo_as_0125.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10wnlo_as_0124.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10wnlo_as_0123.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10wnlo_as_0122.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10wnlo_as_0121.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10wnlo_as_0120.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10wnlo_as_0119.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10wnlo_as_0118.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10wnlo_as_0117.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10wnlo_as_0116.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10wnlo_as_0115.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10wnlo_as_0114.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10wnlo_as_0113.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10wnlo_as_0112.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10wnlo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10wf4.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10wf3.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10was.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10w.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10nnlo_as_0130.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10nnlo_as_0129.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10nnlo_as_0128.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10nnlo_as_0127.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10nnlo_as_0126.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10nnlo_as_0125.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10nnlo_as_0124.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10nnlo_as_0123.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10nnlo_as_0122.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10nnlo_as_0121.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10nnlo_as_0120.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10nnlo_as_0119.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10nnlo_as_0118.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10nnlo_as_0117.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10nnlo_as_0116.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10nnlo_as_0115.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10nnlo_as_0114.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10nnlo_as_0113.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10nnlo_as_0112.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10nnlo_as_0111.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10nnlo_as_0110.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10nnlo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10nlo_nf4.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10nlo_nf3.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10nlo_as_0127.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10nlo_as_0126.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10nlo_as_0125.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10nlo_as_0124.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10nlo_as_0123.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10nlo_as_0122.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10nlo_as_0121.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10nlo_as_0120.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10nlo_as_0119.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10nlo_as_0118.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10nlo_as_0117.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10nlo_as_0116.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10nlo_as_0115.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10nlo_as_0114.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10nlo_as_0113.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10nlo_as_0112.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10nlo.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10f4.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10f3.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10as.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT09MCS.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT09MC2.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT09MC1.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CJ12min.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CJ12mid.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CJ12max.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/Botje_1000.LHpdf
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/Botje_100.LHpdf
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/Alekhin_1000.LHpdf
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/Alekhin_100.LHpdf
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/ATLAS-epWZ12-VAR.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/ATLAS-epWZ12-EIG.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/ACFGPG.LHgrid
wget https://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/ABFKWPI.LHgrid